services:
  backend:
    build: .
    container_name: uzchess-backend-n10
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@database:5432/uzchess-bekend
    command: >
      sh -c "npx typeorm -d dist/data-source.js migration:run && node dist/main.js"
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/uzchess/uploads
    networks:
      - uzchess-n10
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:18-alpine
    container_name: uzchess-database-n10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: uzchess-bekend
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - uzchess-n10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      retries: 5
      interval: 5s
      timeout: 5s
    volumes:
      - uzchess_n10:/var/lib/postgresql

networks:
  uzchess-n10:
    driver: bridge

volumes:
  uzchess_n10: